# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Deploy APp to Azure App Service

on:
  push:
    branches:
      - deploy-to-azure-app-service  

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Maven
      run: mvn clean install -DskipTests
    - name: Upload Artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: springboot-example
        path: ${{ github.workspace }}/target/*.jar
    deploy:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Download Artifact from build job
          uses: actions/download-artifact@v2
          with:
            name: springboot-example
        - name: Deploy to Azure app Service
          uses: actions/webapps-deploy@v2
          with:
            app-name: san-springboot-app-test
            publish-profile: ${{ secrets.azureWebAppPublishProfile }}
            package: '*.jar'
